// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version 2.5.1 DO NOT EDIT.
package apitypes

import (
	"time"
)

// Defines values for AnnotationImageMediaType.
const (
	AnnotationImageMediaTypeImagePng AnnotationImageMediaType = "image/png"
)

// Defines values for BoardRole.
const (
	BoardRoleEditor BoardRole = "editor"
	BoardRoleOwner  BoardRole = "owner"
	BoardRoleViewer BoardRole = "viewer"
)

// Defines values for DiagramKind.
const (
	DiagramKindArchitecture DiagramKind = "architecture"
	DiagramKindEr           DiagramKind = "er"
	DiagramKindMindmap      DiagramKind = "mindmap"
	DiagramKindSequence     DiagramKind = "sequence"
	DiagramKindTodo         DiagramKind = "todo"
)

// Defines values for ErrorCode.
const (
	ErrorCodeAlreadyMember        ErrorCode = "already_member"
	ErrorCodeAuthNotConfigured    ErrorCode = "auth_not_configured"
	ErrorCodeConcurrencyLimited   ErrorCode = "concurrency_limited"
	ErrorCodeContentHashMismatch  ErrorCode = "content_hash_mismatch"
	ErrorCodeCreationIncomplete   ErrorCode = "creation_incomplete"
	ErrorCodeCrossSiteRejected    ErrorCode = "cross_site_rejected"
	ErrorCodeDiagramChatTooLong   ErrorCode = "diagram_chat_too_long"
	ErrorCodeDiagramFailed        ErrorCode = "diagram_failed"
	ErrorCodeForbiddenProject     ErrorCode = "forbidden_project"
	ErrorCodeForbiddenRole        ErrorCode = "forbidden_role"
	ErrorCodeGithubNotConfigured  ErrorCode = "github_not_configured"
	ErrorCodeGithubUnavailable    ErrorCode = "github_unavailable"
	ErrorCodeInternal             ErrorCode = "internal"
	ErrorCodeInterpretationFailed ErrorCode = "interpretation_failed"
	ErrorCodeInvalidInput         ErrorCode = "invalid_input"
	ErrorCodeLastOwner            ErrorCode = "last_owner"
	ErrorCodeLlmNotConfigured     ErrorCode = "llm_not_configured"
	ErrorCodeLlmUnavailable       ErrorCode = "llm_unavailable"
	ErrorCodeLoginRequired        ErrorCode = "login_required"
	ErrorCodeNotFound             ErrorCode = "not_found"
	ErrorCodePreviousItemUnknown  ErrorCode = "previous_item_unknown"
	ErrorCodeProjectFieldMissing  ErrorCode = "project_field_missing"
	ErrorCodeRateLimited          ErrorCode = "rate_limited"
	ErrorCodeSceneConflict        ErrorCode = "scene_conflict"
	ErrorCodeSceneTooLarge        ErrorCode = "scene_too_large"
	ErrorCodeSharingNotConfigured ErrorCode = "sharing_not_configured"
	ErrorCodeTargetLocked         ErrorCode = "target_locked"
	ErrorCodeTargetMismatch       ErrorCode = "target_mismatch"
	ErrorCodeTargetNotSelected    ErrorCode = "target_not_selected"
)

// Defines values for Granularity.
const (
	GranularityEmpty Granularity = ""
	GranularityEpic  Granularity = "epic"
	GranularityIssue Granularity = "issue"
)

// Defines values for ItemKind.
const (
	ItemKindEpic  ItemKind = "epic"
	ItemKindIssue ItemKind = "issue"
)

// Defines values for ProjectAccess.
const (
	ProjectAccessAllowed ProjectAccess = "allowed"
	ProjectAccessDenied  ProjectAccess = "denied"
	ProjectAccessUnknown ProjectAccess = "unknown"
)

// Defines values for SyncAction.
const (
	SyncActionCreated SyncAction = "created"
	SyncActionUpdated SyncAction = "updated"
)

// Defines values for SyncState.
const (
	SyncStateChanged   SyncState = "changed"
	SyncStateCreated   SyncState = "created"
	SyncStateUncreated SyncState = "uncreated"
)

// AnnotationImage 注釈の frame 範囲だけを写した画像。frame の外にある要素は含めない。
//
// サーバーは保存しない。解釈 1 回のあいだ LLM へ渡すためだけに使う
// （ADR 0018）。
type AnnotationImage struct {
	// Data 画像のバイト列を base64 で表したもの。デコード後のバイト数に上限が
	// あり、超えると 400 を返す。上限は超えても縮小せず弾く。黙って劣化
	// させると、渡したはずの情報が消えたことに気づけない（ADR 0018）
	Data []byte `json:"data"`

	// MediaType 画像の MIME タイプ。PNG だけを受け付ける
	MediaType AnnotationImageMediaType `json:"mediaType"`
}

// AnnotationImageMediaType 画像の MIME タイプ。PNG だけを受け付ける
type AnnotationImageMediaType string

// AnnotationStatus 注釈 1 つの状態
type AnnotationStatus struct {
	// Granularity 注釈の粒度。空文字は「指定なし」で、粒度の判断を LLM に任せる。
	Granularity Granularity `json:"granularity"`
	ID          string      `json:"id"`

	// Items この注釈が GitHub に在らしめている draft issue（ADR 0026）。
	//
	// **前回実行で作られたものではなく、run 履歴を itemId で畳んだもの。**
	// 更新は同じ itemId に吸収され、今回触らなかったものも残り続ける。
	// 最新 run だけを返すと、更新のあとに取り残しが画面から消える。
	// 1 件も無ければ省略する
	Items []SyncItem `json:"items,omitempty"`

	// LastSyncedAt 前回実行の時刻。未実行なら省略する
	LastSyncedAt *time.Time `json:"lastSyncedAt,omitempty"`
	Name         string     `json:"name"`

	// State 注釈の 3 状態。保存済みシーンの content_hash と最新 run のそれを
	// 突き合わせて決まる。
	State SyncState `json:"state"`
}

// AuthUser ログイン中の利用者
type AuthUser struct {
	DisplayName string `json:"displayName"`
	Login       string `json:"login"`

	// Provider 認証基盤の識別子。"github" など
	Provider string `json:"provider"`
}

// BoardAccess そのボードで何ができるか。etoki 側と GitHub 側を別々に返す
type BoardAccess struct {
	// ProjectAccess 作成先の Project に書けるかどうかの、いまの状態。
	//
	// - `allowed` … 書ける
	// - `denied` … 書けない。招待されただけで、リポジトリのアクセス権を
	//   持たない利用者がこれになる
	// - `unknown` … 確かめられなかった。GitHub が未設定、作成先が未選択、
	//   問い合わせに失敗した、のどれか。**allowed / denied のどちらにも
	//   倒さない。** 倒すと、確かめていないことを確かめたように見せることになる
	ProjectAccess ProjectAccess `json:"projectAccess"`

	// Role ボードに対する権限の強さ（ADR 0017）。
	//
	// - `owner` … 招待とロール変更、作成先の変更ができる
	// - `editor` … ブレストと解釈と draft issue の作成ができる。作成できるかを
	//   最終的に決めるのは GitHub
	// - `viewer` … 読むだけ。解釈も許さない。解釈は LLM を叩く外部呼び出しで
	//   あり、閲覧者に許すのは「閲覧」ではない
	Role BoardRole `json:"role"`
}

// BoardDeletion ボードを削除したときに etoki から失われるもの（ADR 0042）。
//
// **GitHub 側で何が起きるかは含まれない。** etoki は draft issue を
// 消さないので、GitHub にはそのまま残る。ここが答えるのは「辿れなく
// なるのはどれだけか」という問いのほう。
type BoardDeletion struct {
	// RecordedItemCount そのボードから作成したと etoki が記録している draft issue の件数。
	//
	// 数え方は注釈のカードに出している「いま GitHub に在る N 件」と同じ
	// 畳み込み（ADR 0026）。**GitHub 上でまだ在るかどうかは etoki には
	// 分からない**（ADR 0007）ので、これは記録の件数であって現況では
	// ない
	RecordedItemCount int `json:"recordedItemCount"`
}

// BoardDetail defines model for BoardDetail.
type BoardDetail struct {
	CreatedAt time.Time `json:"createdAt"`
	ID        string    `json:"id"`
	Name      string    `json:"name"`

	// ProjectID draft issue を作る Projects v2 の node ID。未選択なら空文字
	ProjectID string `json:"projectId"`

	// ProjectNumber 作成先 Project の番号。作成先を選んだ時点のスナップショット
	// （ADR 0019）。取得していなければ 0
	ProjectNumber int `json:"projectNumber"`

	// ProjectTitle 作成先 Project の名前。作成先を選んだ時点のスナップショット
	// （ADR 0019）。取得していなければ空文字
	ProjectTitle string `json:"projectTitle"`

	// ProjectURL 作成先 Project の URL。作成先を選んだ時点のスナップショット
	// （ADR 0025）。取得していなければ空文字。
	//
	// 番号から組み立てたものではなく GitHub が返したもの。Projects v2 の
	// URL は owner が user か org かで形が変わり、etoki はどちらなのかを
	// 知らない
	ProjectURL string `json:"projectUrl"`

	// RepositoryName 作成先リポジトリの名前。未選択なら空文字
	RepositoryName string `json:"repositoryName"`

	// RepositoryOwner 作成先リポジトリの所有者。未選択なら空文字
	RepositoryOwner string `json:"repositoryOwner"`

	// Role ボードに対する権限の強さ（ADR 0017）。
	//
	// - `owner` … 招待とロール変更、作成先の変更ができる
	// - `editor` … ブレストと解釈と draft issue の作成ができる。作成できるかを
	//   最終的に決めるのは GitHub
	// - `viewer` … 読むだけ。解釈も許さない。解釈は LLM を叩く外部呼び出しで
	//   あり、閲覧者に許すのは「閲覧」ではない
	Role BoardRole `json:"role"`

	// Scene Excalidraw のシーン JSON をそのまま入れた文字列
	Scene string `json:"scene"`

	// TargetLocked 作成先を変更できないことを表す。そのボードで draft issue を
	// 1 件でも作ると立つ（ADR 0014）。フロントは sync_runs を
	// 数えられないので、状態としてサーバーが返す
	TargetLocked bool      `json:"targetLocked"`
	UpdatedAt    time.Time `json:"updatedAt"`
}

// BoardMember ボードのメンバー 1 人
type BoardMember struct {
	CreatedAt   time.Time `json:"createdAt"`
	DisplayName string    `json:"displayName"`

	// Login 認証基盤上のログイン名。表示用。移行前のボードなど、利用者を
	// 引けない場合は空文字になる
	Login string `json:"login"`

	// Role ボードに対する権限の強さ（ADR 0017）。
	//
	// - `owner` … 招待とロール変更、作成先の変更ができる
	// - `editor` … ブレストと解釈と draft issue の作成ができる。作成できるかを
	//   最終的に決めるのは GitHub
	// - `viewer` … 読むだけ。解釈も許さない。解釈は LLM を叩く外部呼び出しで
	//   あり、閲覧者に許すのは「閲覧」ではない
	Role BoardRole `json:"role"`

	// UserID etoki が発番した ID。指し先にはこれを使う
	UserID string `json:"userId"`
}

// BoardRole ボードに対する権限の強さ（ADR 0017）。
//
//   - `owner` … 招待とロール変更、作成先の変更ができる
//   - `editor` … ブレストと解釈と draft issue の作成ができる。作成できるかを
//     最終的に決めるのは GitHub
//   - `viewer` … 読むだけ。解釈も許さない。解釈は LLM を叩く外部呼び出しで
//     あり、閲覧者に許すのは「閲覧」ではない
type BoardRole string

// BoardSummary 一覧で返すボード。シーンは大きいので含めない。
//
// 作成先は含める。一覧をリポジトリと Project でまとめて見せるため
// （ADR 0019）。含めないのは `targetLocked` だけで、これは算出に run の
// 照会が要り、ボード数だけ問い合わせが増える。
type BoardSummary struct {
	CreatedAt time.Time `json:"createdAt"`
	ID        string    `json:"id"`
	Name      string    `json:"name"`

	// ProjectID draft issue を作る Projects v2 の node ID。未選択なら空文字
	ProjectID string `json:"projectId"`

	// ProjectNumber 作成先 Project の番号。作成先を選んだ時点のスナップショット
	// （ADR 0019）。取得していなければ 0
	ProjectNumber int `json:"projectNumber"`

	// ProjectTitle 作成先 Project の名前。作成先を選んだ時点のスナップショット
	// （ADR 0019）。取得していなければ空文字
	ProjectTitle string `json:"projectTitle"`

	// ProjectURL 作成先 Project の URL。作成先を選んだ時点のスナップショット
	// （ADR 0025）。取得していなければ空文字。
	//
	// 番号から組み立てたものではなく GitHub が返したもの。Projects v2 の
	// URL は owner が user か org かで形が変わり、etoki はどちらなのかを
	// 知らない
	ProjectURL string `json:"projectUrl"`

	// RepositoryName 作成先リポジトリの名前。未選択なら空文字
	RepositoryName string `json:"repositoryName"`

	// RepositoryOwner 作成先リポジトリの所有者。未選択なら空文字
	RepositoryOwner string `json:"repositoryOwner"`

	// Role ボードに対する権限の強さ（ADR 0017）。
	//
	// - `owner` … 招待とロール変更、作成先の変更ができる
	// - `editor` … ブレストと解釈と draft issue の作成ができる。作成できるかを
	//   最終的に決めるのは GitHub
	// - `viewer` … 読むだけ。解釈も許さない。解釈は LLM を叩く外部呼び出しで
	//   あり、閲覧者に許すのは「閲覧」ではない
	Role      BoardRole `json:"role"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// BoardTarget draft issue の作成先。設定のリクエストボディ。
//
// リポジトリと Project の両方を持つ。保存先として効くのは projectId
// だが、どのリポジトリから選んだかを画面に出すために owner / name も残す。
//
// projectNumber と projectTitle と projectUrl は**表示用のスナップショット**
// であり、作成先そのものではない（ADR 0019 / 0025）。未選択の判定にも、
// 固定済みかどうかの判定にも使わない。選ばせた画面が見せていたものを
// そのまま送る。
//
// 表示用の 3 つは任意。省略すると「知らない」（0 と空文字）として保存する。
// 必須にすると、画面を通さない呼び出し側が値をでっち上げることになる。
type BoardTarget struct {
	ProjectID       string `json:"projectId"`
	ProjectNumber   int    `json:"projectNumber,omitempty"`
	ProjectTitle    string `json:"projectTitle,omitempty"`
	ProjectURL      string `json:"projectUrl,omitempty"`
	RepositoryName  string `json:"repositoryName"`
	RepositoryOwner string `json:"repositoryOwner"`
}

// BoardTargetDisplay 作成先の表示用スナップショット。取り直しのリクエストボディ（ADR 0037）。
//
// `projectId` は**変更先ではなく照合材料**。どの作成先の表示名なのかを
// 示すために伴い、保存されているものと違えば 409 になる。リポジトリを
// 持たないのは、この口で作成先そのものを動かせないことを形で示すため。
//
// 表示用の 3 つは任意。省略すると「知らない」（0 と空文字）として保存
// する。BoardTarget と同じ扱いにしてあるので、GitHub が URL を返さない
// Project でも取り直せる。
type BoardTargetDisplay struct {
	// ProjectID いま保存されている作成先の Projects v2 node ID
	ProjectID     string `json:"projectId"`
	ProjectNumber int    `json:"projectNumber,omitempty"`
	ProjectTitle  string `json:"projectTitle,omitempty"`
	ProjectURL    string `json:"projectUrl,omitempty"`
}

// Capabilities いま使える機能。**プロセスの設定であって、利用者ごとの権限ではない。**
//
// false のものは押す前に理由を出すために使う。理由の文言は `ErrorCode` の
// `*_not_configured` と同じものを引く。そのエンドポイントを叩けば同じ
// 原因で 503 が返るので、**先に見せる文言と後から返る理由を別に持たない。**
type Capabilities struct {
	// Creation draft issue を作れるか。false は GitHub が未設定。**作成先の候補も
	// 引けない**ので、新しいボードも作れない（ADR 0017）
	Creation bool `json:"creation"`

	// DiagramDraft プロンプトから図のドラフトを生成できるか。false は LLM が未設定。
	//
	// **`interpretation` と畳まない。** 未設定の理由も設定するものも
	// 同じだが、答えている問いが違う。1 つにすると、画面はどちらの
	// ボタンを止めればよいのかをこの値から決められなくなる
	DiagramDraft bool `json:"diagramDraft"`

	// Interpretation 注釈を解釈できるか。false は LLM が未設定（ADR 0008）
	Interpretation bool `json:"interpretation"`

	// Sharing ボードを共有できるか。false は認証が未設定。招待は「誰であるか」が
	// 決まって初めて意味を持つ（ADR 0016 / 0017）
	Sharing bool `json:"sharing"`
}

// CreateBoardRequest ボード作成のリクエストボディ。
//
// **作成先は必須。** 候補は `minPermissionLevel: WRITE` で絞ってあるので
// （ADR 0014）、書ける Project を 1 つも持たない人はボードを作れない。
// 「ボードの作成にはリポジトリへのアクセス権が要る」はこれで満ちる
// （ADR 0017）。
//
// 副産物として、作成先が未選択のボードは新規には生まれなくなる。移行前の
// ボードは未選択のまま残るので、`projectId` が空文字の経路は消えない。
type CreateBoardRequest struct {
	Name string `json:"name"`

	// ProjectID draft issue を作る Projects v2 の node ID
	ProjectID string `json:"projectId"`

	// ProjectNumber 作成先 Project の番号。表示用のスナップショット（ADR 0019）。
	// 省略すると 0（名前を知らない）で保存する
	ProjectNumber int `json:"projectNumber,omitempty"`

	// ProjectTitle 作成先 Project の名前。表示用のスナップショット（ADR 0019）。
	// 省略すると空文字（名前を知らない）で保存する
	ProjectTitle string `json:"projectTitle,omitempty"`

	// ProjectURL 作成先 Project の URL。表示用のスナップショット（ADR 0025）。
	// 省略すると空文字（URL を知らない）で保存する
	ProjectURL      string `json:"projectUrl,omitempty"`
	RepositoryName  string `json:"repositoryName"`
	RepositoryOwner string `json:"repositoryOwner"`

	// Scene 省略すると空のシーンで作る
	Scene string `json:"scene,omitempty"`
}

// CreatedRun 作成した run。途中で失敗しても、作れたぶんは items に入る
type CreatedRun struct {
	CreatedAt time.Time `json:"createdAt"`

	// Error 途中で失敗した理由
	Error string `json:"error,omitempty"`

	// Incomplete 途中で失敗したことを表す
	Incomplete bool       `json:"incomplete,omitempty"`
	Items      []SyncItem `json:"items"`
	RunID      int64      `json:"runId"`
}

// DiagramDraft 生成した図のドラフト。**キャンバスには置かれていない。** 置くかどうかは
// 見てから開発者が決める（中核思想 3）。mermaid を Excalidraw の要素に
// するのはフロントの仕事（ADR 0040）。
type DiagramDraft struct {
	// Kind 図の種類。**語彙はここ 1 つ**で、ブレストの出発点になるテンプレートと、
	// プロンプトから生成するドラフトが同じ 5 種を指す。
	//
	// - `todo` … やることの洗い出し
	// - `mindmap` … 発想の広げ方
	// - `sequence` … 登場人物とやりとりの順序
	// - `er` … 実体と関連
	// - `architecture` … 構成要素と境界
	//
	// **どの mermaid 記法で書くかはサーバーが決める**（ADR 0041）。
	// `mindmap` と `architecture` は mermaid にも同名の記法があるが、
	// Excalidraw の要素に分解できず画像 1 枚になるため使わない（ADR 0040）。
	Kind DiagramKind `json:"kind"`

	// Mermaid 生成された mermaid。コードフェンスは外してある
	Mermaid string `json:"mermaid"`

	// TurnsRemaining このあと何往復できるか。**上限に当たってから知らせるのでは遅い**
	// ので、押す前に見えるようにしている
	TurnsRemaining int `json:"turnsRemaining"`
}

// DiagramKind 図の種類。**語彙はここ 1 つ**で、ブレストの出発点になるテンプレートと、
// プロンプトから生成するドラフトが同じ 5 種を指す。
//
// - `todo` … やることの洗い出し
// - `mindmap` … 発想の広げ方
// - `sequence` … 登場人物とやりとりの順序
// - `er` … 実体と関連
// - `architecture` … 構成要素と境界
//
// **どの mermaid 記法で書くかはサーバーが決める**（ADR 0041）。
// `mindmap` と `architecture` は mermaid にも同名の記法があるが、
// Excalidraw の要素に分解できず画像 1 枚になるため使わない（ADR 0040）。
type DiagramKind string

// DiagramTurn 図のドラフトを直してきたやりとり 1 往復。
//
// **サーバーは会話を保存しない**（ADR 0041）ので、ここまでの往復は毎回
// まるごと送る。会話は成果物ではなく、成果物はキャンバス。
type DiagramTurn struct {
	// Mermaid それに対して返った mermaid
	Mermaid string `json:"mermaid"`

	// Prompt そのとき書いた指示
	Prompt string `json:"prompt"`
}

// ErrorCode 失敗の原因を表す機械可読な符号。**画面はこれで打ち手を分ける。**
//
// ステータスだけでは打ち手が決まらない。409 には「開き直す」「諦める」
// 「解釈からやり直す」「入力を変える」が同居していて、利用者がすべきことは
// すべて違う。403 も etoki のロール不足（`forbidden_role`）と GitHub 側の
// 拒否（`forbidden_project`）で直す場所が違い、2 層に分けて持つと決めた
// （ADR 0017）のに、文言に畳むと画面でその区別が消える。
//
// **`*_not_configured` を 1 つに畳まない。** 設定するものが違うので、
// 畳むと画面が「何を設定すればよいか」を言えなくなる。
type ErrorCode string

// ErrorResponse 失敗したときの本文。打ち手は `code` で分け、`error` は手掛かりに留める。
type ErrorResponse struct {
	// Code 失敗の原因を表す機械可読な符号。**画面はこれで打ち手を分ける。**
	//
	// ステータスだけでは打ち手が決まらない。409 には「開き直す」「諦める」
	// 「解釈からやり直す」「入力を変える」が同居していて、利用者がすべきことは
	// すべて違う。403 も etoki のロール不足（`forbidden_role`）と GitHub 側の
	// 拒否（`forbidden_project`）で直す場所が違い、2 層に分けて持つと決めた
	// （ADR 0017）のに、文言に畳むと画面でその区別が消える。
	//
	// **`*_not_configured` を 1 つに畳まない。** 設定するものが違うので、
	// 畳むと画面が「何を設定すればよいか」を言えなくなる。
	Code ErrorCode `json:"code"`

	// Error 原因の手掛かり。**利用者向けの文言ではない。** 画面は既定で畳む。
	// GitHub や LLM が返した本文が実際の手掛かりになる経路があるので残す
	Error string `json:"error"`
}

// GenerateDiagramRequest 図のドラフトを 1 つ作るための入力。**保存済みシーンもキャンバスも
// 読まない**（ADR 0041）ので、未保存でも使える。
type GenerateDiagramRequest struct {
	// History ここまでのやりとり。1 回目は空。**上限を超えたら黙って古いものを
	// 捨てず、`diagram_chat_too_long` で返す**
	History *[]DiagramTurn `json:"history,omitempty"`

	// Kind 図の種類。**語彙はここ 1 つ**で、ブレストの出発点になるテンプレートと、
	// プロンプトから生成するドラフトが同じ 5 種を指す。
	//
	// - `todo` … やることの洗い出し
	// - `mindmap` … 発想の広げ方
	// - `sequence` … 登場人物とやりとりの順序
	// - `er` … 実体と関連
	// - `architecture` … 構成要素と境界
	//
	// **どの mermaid 記法で書くかはサーバーが決める**（ADR 0041）。
	// `mindmap` と `architecture` は mermaid にも同名の記法があるが、
	// Excalidraw の要素に分解できず画像 1 枚になるため使わない（ADR 0040）。
	Kind DiagramKind `json:"kind"`

	// Prompt 今回の指示。空白だけのものは 400 で弾く。既定に倒さないのは、
	// 何を描くかが入力そのものであるため
	Prompt string `json:"prompt"`
}

// Granularity 注釈の粒度。空文字は「指定なし」で、粒度の判断を LLM に任せる。
type Granularity string

// HealthResponse /healthz のレスポンスボディ
type HealthResponse struct {
	Status string `json:"status"`
}

// InterpretRequest 解釈のリクエストボディ。テキストは保存済みシーンから取るので、ここには
// シーンから作れないものだけを載せる。
type InterpretRequest struct {
	// Image 注釈の frame 範囲だけを写した画像。frame の外にある要素は含めない。
	//
	// サーバーは保存しない。解釈 1 回のあいだ LLM へ渡すためだけに使う
	// （ADR 0018）。
	Image *AnnotationImage `json:"image,omitempty"`
}

// Interpretation LLM が注釈をどう解釈したか。
//
// `summary` は GitHub には作らない。作成前に「こう読んだ」を見せるためだけに
// 使う（ADR 0006）。
//
// 作成のリクエストボディとしてもこの形をそのまま使う。開発者が確認した
// 結果を送り返す、という流れなので別の型にしない。
type Interpretation struct {
	// ContentHash 解釈の入力になった保存済みシーンのハッシュ。フロントでは組み立てず、
	// 受け取ったものをそのまま送り返す
	ContentHash string            `json:"contentHash"`
	Items       []InterpretedItem `json:"items"`
	Summary     string            `json:"summary"`
}

// InterpretedItem 解釈結果に含まれる draft issue 1 件。まだ作成はしていない
type InterpretedItem struct {
	Body string `json:"body"`

	// Kind GitHub に作る draft issue の種別。作るのは epic と issue の 2 階層のみ
	// （ADR 0006）。
	Kind          ItemKind `json:"kind"`
	LocalID       string   `json:"localId"`
	ParentLocalID string   `json:"parentLocalId,omitempty"`

	// PreviousItemID 書き換える対象の itemId（ADR 0026）。新しく作るなら省略する。
	//
	// 解釈のレスポンスでは LLM が対応づけた候補が入る。作成のリクエストでは
	// 開発者が確かめた結果として送り返す。**サーバーはこの値がその注釈の
	// ものであることを確かめる。** 確かめずに通すと、任意の node ID を
	// 書いて無関係な draft issue を書き換えられる
	PreviousItemID string `json:"previousItemId,omitempty"`
	Title          string `json:"title"`
}

// InviteMemberRequest 招待のリクエストボディ
type InviteMemberRequest struct {
	// Login 招待する相手の login。一度 etoki にログインしている必要がある
	Login string `json:"login"`

	// Role ボードに対する権限の強さ（ADR 0017）。
	//
	// - `owner` … 招待とロール変更、作成先の変更ができる
	// - `editor` … ブレストと解釈と draft issue の作成ができる。作成できるかを
	//   最終的に決めるのは GitHub
	// - `viewer` … 読むだけ。解釈も許さない。解釈は LLM を叩く外部呼び出しで
	//   あり、閲覧者に許すのは「閲覧」ではない
	Role BoardRole `json:"role"`
}

// ItemKind GitHub に作る draft issue の種別。作るのは epic と issue の 2 階層のみ
// （ADR 0006）。
type ItemKind string

// LoginResponse 認可画面へ送り出すための URL
type LoginResponse struct {
	AuthorizeURL string `json:"authorizeUrl"`
}

// Project リポジトリに紐づく Projects v2
type Project struct {
	// ID GraphQL の node ID。作成先として保存するのはこれ
	ID string `json:"id"`

	// Number リポジトリ内での番号。GitHub の URL に出る
	Number int    `json:"number"`
	Title  string `json:"title"`

	// URL Project のページ。**番号から組み立てず GitHub が返したものを運ぶ。**
	// Projects v2 の URL は owner が user か org かで形が変わり、etoki は
	// どちらなのかを知らない（ADR 0025）
	URL string `json:"url"`
}

// ProjectAccess 作成先の Project に書けるかどうかの、いまの状態。
//
//   - `allowed` … 書ける
//   - `denied` … 書けない。招待されただけで、リポジトリのアクセス権を
//     持たない利用者がこれになる
//   - `unknown` … 確かめられなかった。GitHub が未設定、作成先が未選択、
//     問い合わせに失敗した、のどれか。**allowed / denied のどちらにも
//     倒さない。** 倒すと、確かめていないことを確かめたように見せることになる
type ProjectAccess string

// RenameBoardRequest 改名のリクエストボディ。
//
// 名前だけを持つ。作成先やシーンを一緒に送れる形にすると、この経路でも
// 作成先を書けることになり、固定（ADR 0014）が意味を失う。
type RenameBoardRequest struct {
	// Name 新しい名前。空文字と空白だけは弾く
	Name string `json:"name"`
}

// Repository 作成先を選ぶときに見せるリポジトリ
type Repository struct {
	Description string `json:"description,omitempty"`
	Name        string `json:"name"`
	Owner       string `json:"owner"`
}

// SaveSceneRequest シーン保存のリクエストボディ。
//
// `baseUpdatedAt` は任意にしない。任意にすると API を直接叩く経路で照合を
// 素通りでき、防ぎたい後勝ちがそのまま残る（ADR 0010 と同じ理由）。
type SaveSceneRequest struct {
	// BaseUpdatedAt 編集の基準にしたボードの `updatedAt`。取得時に返ったものをそのまま
	// 送り返す。現在の版と違えば 409 になり、シーンは書き換わらない
	// （ADR 0020）
	BaseUpdatedAt time.Time `json:"baseUpdatedAt"`
	Scene         string    `json:"scene"`
}

// SaveSceneResponse 保存後のボードの版。
//
// 返さないと、クライアントは保存のたびにボードを取り直さないと次の保存が
// できない。取り直すとシーンまで運ぶことになる。
type SaveSceneResponse struct {
	// UpdatedAt 保存後の `updatedAt`。次の保存の `baseUpdatedAt` になる
	UpdatedAt time.Time `json:"updatedAt"`
}

// SessionStatus ログイン状態。認証を設定していない構成でも 200 で返る。
type SessionStatus struct {
	// AuthRequired 認証を設定しているか。false なら画面はログインを求めない
	AuthRequired  bool `json:"authRequired"`
	Authenticated bool `json:"authenticated"`

	// User ログイン中の利用者
	User *AuthUser `json:"user,omitempty"`
}

// SetMemberRoleRequest ロール変更のリクエストボディ
type SetMemberRoleRequest struct {
	// Role ボードに対する権限の強さ（ADR 0017）。
	//
	// - `owner` … 招待とロール変更、作成先の変更ができる
	// - `editor` … ブレストと解釈と draft issue の作成ができる。作成できるかを
	//   最終的に決めるのは GitHub
	// - `viewer` … 読むだけ。解釈も許さない。解釈は LLM を叩く外部呼び出しで
	//   あり、閲覧者に許すのは「閲覧」ではない
	Role BoardRole `json:"role"`
}

// SyncAction 1 つの run がその item に対して何をしたか（ADR 0026）。
//
// `created` は新しく作った、`updated` は既存の draft issue を書き換えた。
// 記録していなかった頃の run はすべて `created`。当時は更新の経路が無かった。
type SyncAction string

// SyncItem 作成済みの draft issue 1 件
type SyncItem struct {
	// Action 1 つの run がその item に対して何をしたか（ADR 0026）。
	//
	// `created` は新しく作った、`updated` は既存の draft issue を書き換えた。
	// 記録していなかった頃の run はすべて `created`。当時は更新の経路が無かった。
	Action SyncAction `json:"action"`

	// Body 作成時の本文。記録していなかった頃の run では空
	Body string `json:"body"`

	// ItemID GitHub Projects v2 の item ID
	ItemID string `json:"itemId"`

	// Kind GitHub に作る draft issue の種別。作るのは epic と issue の 2 階層のみ
	// （ADR 0006）。
	Kind ItemKind `json:"kind"`

	// LocalID 解釈結果の中でだけ通じる ID。親子の対応づけに使う
	LocalID string `json:"localId"`

	// ParentLocalID epic に属する issue のとき、その epic の localId
	ParentLocalID string `json:"parentLocalId,omitempty"`
	Title         string `json:"title"`
}

// SyncRun 1 つの注釈に対する 1 回ぶんの実行の記録（ADR 0007）。
//
// **「そのときの全体像」ではなく「その 1 回で何をしたか」**（ADR 0026）。
// 触らなかった item はここには現れない。いま GitHub に在るものが知りたい
// なら `AnnotationStatus.items`（畳み込み）を見る。
type SyncRun struct {
	// CreatedAt 実行の時刻
	CreatedAt time.Time `json:"createdAt"`

	// ID run の識別子。**新しさの順はこれで決まる**（時刻は呼び出し側が
	// 与えるので、同じ値の run がありうる）
	ID int64 `json:"id"`

	// Items その run で作成または更新した draft issue。**空配列がありうる。**
	// 1 件も作れずに終わった run も記録として残る（ADR 0009）
	Items []SyncItem `json:"items"`
}

// SyncState 注釈の 3 状態。保存済みシーンの content_hash と最新 run のそれを
// 突き合わせて決まる。
type SyncState string

// AnnotationID defines model for AnnotationId.
type AnnotationID = string

// BoardID defines model for BoardId.
type BoardID = string

// RepositoryName defines model for RepositoryName.
type RepositoryName = string

// RepositoryOwner defines model for RepositoryOwner.
type RepositoryOwner = string

// UserID defines model for UserId.
type UserID = string

// BadRequest 失敗したときの本文。打ち手は `code` で分け、`error` は手掛かりに留める。
type BadRequest = ErrorResponse

// DiagramChatTooLong 失敗したときの本文。打ち手は `code` で分け、`error` は手掛かりに留める。
type DiagramChatTooLong = ErrorResponse

// Forbidden 失敗したときの本文。打ち手は `code` で分け、`error` は手掛かりに留める。
type Forbidden = ErrorResponse

// InternalError 失敗したときの本文。打ち手は `code` で分け、`error` は手掛かりに留める。
type InternalError = ErrorResponse

// NotConfigured 失敗したときの本文。打ち手は `code` で分け、`error` は手掛かりに留める。
type NotConfigured = ErrorResponse

// NotFound 失敗したときの本文。打ち手は `code` で分け、`error` は手掛かりに留める。
type NotFound = ErrorResponse

// SceneTooLarge 失敗したときの本文。打ち手は `code` で分け、`error` は手掛かりに留める。
type SceneTooLarge = ErrorResponse

// TooManyRequests 失敗したときの本文。打ち手は `code` で分け、`error` は手掛かりに留める。
type TooManyRequests = ErrorResponse

// Unauthorized 失敗したときの本文。打ち手は `code` で分け、`error` は手掛かりに留める。
type Unauthorized = ErrorResponse

// CompleteLoginParams defines parameters for CompleteLogin.
type CompleteLoginParams struct {
	Code  string `form:"code" json:"code"`
	State string `form:"state" json:"state"`
}

// CreateBoardJSONRequestBody defines body for CreateBoard for application/json ContentType.
type CreateBoardJSONRequestBody = CreateBoardRequest

// RenameBoardJSONRequestBody defines body for RenameBoard for application/json ContentType.
type RenameBoardJSONRequestBody = RenameBoardRequest

// InterpretAnnotationJSONRequestBody defines body for InterpretAnnotation for application/json ContentType.
type InterpretAnnotationJSONRequestBody = InterpretRequest

// CreateItemsJSONRequestBody defines body for CreateItems for application/json ContentType.
type CreateItemsJSONRequestBody = Interpretation

// GenerateDiagramDraftJSONRequestBody defines body for GenerateDiagramDraft for application/json ContentType.
type GenerateDiagramDraftJSONRequestBody = GenerateDiagramRequest

// InviteBoardMemberJSONRequestBody defines body for InviteBoardMember for application/json ContentType.
type InviteBoardMemberJSONRequestBody = InviteMemberRequest

// SetBoardMemberRoleJSONRequestBody defines body for SetBoardMemberRole for application/json ContentType.
type SetBoardMemberRoleJSONRequestBody = SetMemberRoleRequest

// SaveSceneJSONRequestBody defines body for SaveScene for application/json ContentType.
type SaveSceneJSONRequestBody = SaveSceneRequest

// SetBoardTargetJSONRequestBody defines body for SetBoardTarget for application/json ContentType.
type SetBoardTargetJSONRequestBody = BoardTarget

// RefreshBoardTargetDisplayJSONRequestBody defines body for RefreshBoardTargetDisplay for application/json ContentType.
type RefreshBoardTargetDisplayJSONRequestBody = BoardTargetDisplay
