// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version 2.5.1 DO NOT EDIT.
package apitypes

import (
	"time"
)

// Defines values for Granularity.
const (
	GranularityEmpty Granularity = ""
	GranularityEpic  Granularity = "epic"
	GranularityIssue Granularity = "issue"
)

// Defines values for ItemKind.
const (
	ItemKindEpic  ItemKind = "epic"
	ItemKindIssue ItemKind = "issue"
)

// Defines values for SyncState.
const (
	SyncStateChanged   SyncState = "changed"
	SyncStateCreated   SyncState = "created"
	SyncStateUncreated SyncState = "uncreated"
)

// AnnotationStatus 注釈 1 つの状態
type AnnotationStatus struct {
	// Granularity 注釈の粒度。空文字は「指定なし」で、粒度の判断を LLM に任せる。
	Granularity Granularity `json:"granularity"`
	ID          string      `json:"id"`

	// Items 前回実行で作られた draft issue。未実行なら省略する
	Items []SyncItem `json:"items,omitempty"`

	// LastSyncedAt 前回実行の時刻。未実行なら省略する
	LastSyncedAt *time.Time `json:"lastSyncedAt,omitempty"`
	Name         string     `json:"name"`

	// State 注釈の 3 状態。保存済みシーンの content_hash と最新 run のそれを
	// 突き合わせて決まる。
	State SyncState `json:"state"`
}

// AuthUser ログイン中の利用者
type AuthUser struct {
	DisplayName string `json:"displayName"`
	Login       string `json:"login"`

	// Provider 認証基盤の識別子。"github" など
	Provider string `json:"provider"`
}

// BoardDetail defines model for BoardDetail.
type BoardDetail struct {
	CreatedAt time.Time `json:"createdAt"`
	ID        string    `json:"id"`
	Name      string    `json:"name"`

	// ProjectID draft issue を作る Projects v2 の node ID。未選択なら空文字
	ProjectID string `json:"projectId"`

	// RepositoryName 作成先リポジトリの名前。未選択なら空文字
	RepositoryName string `json:"repositoryName"`

	// RepositoryOwner 作成先リポジトリの所有者。未選択なら空文字
	RepositoryOwner string `json:"repositoryOwner"`

	// Scene Excalidraw のシーン JSON をそのまま入れた文字列
	Scene string `json:"scene"`

	// TargetLocked 作成先を変更できないことを表す。そのボードで draft issue を
	// 1 件でも作ると立つ（ADR 0014）。フロントは sync_runs を
	// 数えられないので、状態としてサーバーが返す
	TargetLocked bool      `json:"targetLocked"`
	UpdatedAt    time.Time `json:"updatedAt"`
}

// BoardSummary 一覧で返すボード。シーンは大きいので含めない
type BoardSummary struct {
	CreatedAt time.Time `json:"createdAt"`
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// BoardTarget draft issue の作成先。設定のリクエストボディ。
//
// リポジトリと Project の両方を持つ。保存先として効くのは projectId
// だが、どのリポジトリから選んだかを画面に出すために owner / name も残す。
type BoardTarget struct {
	ProjectID       string `json:"projectId"`
	RepositoryName  string `json:"repositoryName"`
	RepositoryOwner string `json:"repositoryOwner"`
}

// CreateBoardRequest ボード作成のリクエストボディ
type CreateBoardRequest struct {
	Name string `json:"name"`

	// Scene 省略すると空のシーンで作る
	Scene string `json:"scene,omitempty"`
}

// CreatedRun 作成した run。途中で失敗しても、作れたぶんは items に入る
type CreatedRun struct {
	CreatedAt time.Time `json:"createdAt"`

	// Error 途中で失敗した理由
	Error string `json:"error,omitempty"`

	// Incomplete 途中で失敗したことを表す
	Incomplete bool       `json:"incomplete,omitempty"`
	Items      []SyncItem `json:"items"`
	RunID      int64      `json:"runId"`
}

// ErrorResponse 失敗したときの本文。内部情報は載せない。原因の詳細はサーバー側のログに残す。
type ErrorResponse struct {
	Error string `json:"error"`
}

// Granularity 注釈の粒度。空文字は「指定なし」で、粒度の判断を LLM に任せる。
type Granularity string

// HealthResponse /healthz のレスポンスボディ
type HealthResponse struct {
	Status string `json:"status"`
}

// Interpretation LLM が注釈をどう解釈したか。
//
// `summary` は GitHub には作らない。作成前に「こう読んだ」を見せるためだけに
// 使う（ADR 0006）。
//
// 作成のリクエストボディとしてもこの形をそのまま使う。開発者が確認した
// 結果を送り返す、という流れなので別の型にしない。
type Interpretation struct {
	// ContentHash 解釈の入力になった保存済みシーンのハッシュ。フロントでは組み立てず、
	// 受け取ったものをそのまま送り返す
	ContentHash string            `json:"contentHash"`
	Items       []InterpretedItem `json:"items"`
	Summary     string            `json:"summary"`
}

// InterpretedItem 解釈結果に含まれる draft issue 1 件。まだ作成はしていない
type InterpretedItem struct {
	Body string `json:"body"`

	// Kind GitHub に作る draft issue の種別。作るのは epic と issue の 2 階層のみ
	// （ADR 0006）。
	Kind          ItemKind `json:"kind"`
	LocalID       string   `json:"localId"`
	ParentLocalID string   `json:"parentLocalId,omitempty"`
	Title         string   `json:"title"`
}

// ItemKind GitHub に作る draft issue の種別。作るのは epic と issue の 2 階層のみ
// （ADR 0006）。
type ItemKind string

// LoginResponse 認可画面へ送り出すための URL
type LoginResponse struct {
	AuthorizeURL string `json:"authorizeUrl"`
}

// Project リポジトリに紐づく Projects v2
type Project struct {
	// ID GraphQL の node ID。作成先として保存するのはこれ
	ID string `json:"id"`

	// Number リポジトリ内での番号。GitHub の URL に出る
	Number int    `json:"number"`
	Title  string `json:"title"`
}

// Repository 作成先を選ぶときに見せるリポジトリ
type Repository struct {
	Description string `json:"description,omitempty"`
	Name        string `json:"name"`
	Owner       string `json:"owner"`
}

// SaveSceneRequest シーン保存のリクエストボディ
type SaveSceneRequest struct {
	Scene string `json:"scene"`
}

// SessionStatus ログイン状態。認証を設定していない構成でも 200 で返る。
type SessionStatus struct {
	// AuthRequired 認証を設定しているか。false なら画面はログインを求めない
	AuthRequired  bool `json:"authRequired"`
	Authenticated bool `json:"authenticated"`

	// User ログイン中の利用者
	User *AuthUser `json:"user,omitempty"`
}

// SyncItem 作成済みの draft issue 1 件
type SyncItem struct {
	// ItemID GitHub Projects v2 の item ID
	ItemID string `json:"itemId"`

	// Kind GitHub に作る draft issue の種別。作るのは epic と issue の 2 階層のみ
	// （ADR 0006）。
	Kind ItemKind `json:"kind"`

	// LocalID 解釈結果の中でだけ通じる ID。親子の対応づけに使う
	LocalID string `json:"localId"`

	// ParentLocalID epic に属する issue のとき、その epic の localId
	ParentLocalID string `json:"parentLocalId,omitempty"`
	Title         string `json:"title"`
}

// SyncState 注釈の 3 状態。保存済みシーンの content_hash と最新 run のそれを
// 突き合わせて決まる。
type SyncState string

// AnnotationID defines model for AnnotationId.
type AnnotationID = string

// BoardID defines model for BoardId.
type BoardID = string

// RepositoryName defines model for RepositoryName.
type RepositoryName = string

// RepositoryOwner defines model for RepositoryOwner.
type RepositoryOwner = string

// BadRequest 失敗したときの本文。内部情報は載せない。原因の詳細はサーバー側のログに残す。
type BadRequest = ErrorResponse

// Forbidden 失敗したときの本文。内部情報は載せない。原因の詳細はサーバー側のログに残す。
type Forbidden = ErrorResponse

// InternalError 失敗したときの本文。内部情報は載せない。原因の詳細はサーバー側のログに残す。
type InternalError = ErrorResponse

// NotFound 失敗したときの本文。内部情報は載せない。原因の詳細はサーバー側のログに残す。
type NotFound = ErrorResponse

// Unauthorized 失敗したときの本文。内部情報は載せない。原因の詳細はサーバー側のログに残す。
type Unauthorized = ErrorResponse

// CompleteLoginParams defines parameters for CompleteLogin.
type CompleteLoginParams struct {
	Code  string `form:"code" json:"code"`
	State string `form:"state" json:"state"`
}

// CreateBoardJSONRequestBody defines body for CreateBoard for application/json ContentType.
type CreateBoardJSONRequestBody = CreateBoardRequest

// CreateItemsJSONRequestBody defines body for CreateItems for application/json ContentType.
type CreateItemsJSONRequestBody = Interpretation

// SaveSceneJSONRequestBody defines body for SaveScene for application/json ContentType.
type SaveSceneJSONRequestBody = SaveSceneRequest

// SetBoardTargetJSONRequestBody defines body for SetBoardTarget for application/json ContentType.
type SetBoardTargetJSONRequestBody = BoardTarget
